name: Automatically Deploy Javadocs

on:
  push:
    branches: [ main ]

jobs:
   build:

      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Javadocs
        run: |
         echo "Building javadocs with gradle"
         ./gradlew javadoc
         echo "Moving to javadocs directory:"
         cd build/docs/javadoc/
         echo "Creating .nojekyll to have Github pages deploy html as is:"
         touch .nojekyll
         
      #- name: Deploy
      #  uses: JamesIves/github-pages-deploy-action@4.0.0
      #  with:
      #    branch: main # The branch the action should deploy to.
      #    folder: build/docs/javadoc/ # The folder the action should deploy.

      - name: Copy to Documentation Website Location
        run: |
         rm -rf docs
         cp -rf build/docs/javadoc/. docs
      - name: Commit documentation changes
        run: |
         if [[ `git status --porcelain` ]]; then
           git config --global user.name 'sakaki000'
           git config --global user.email 'terawaki.t.saze@gmail.com'
           git add -A
           git commit -m "Automated API website updates."
         fi
