name: Javadoc Check
on: workflow_dispatch
#  push:
#    branches: [ main_** ]
#    paths: 
#    - 'first/src/**'
#    - 'second/src/**'

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - name: Echo Value
        run: echo "Javadoc Check"
