name: Automatically Deploy Javadocs

on: [push, pull_request]

jobs:
   build:
   
     runs-on: ubuntu-latest
     
     steps:
        - uses: actions/checkout@v2
        - name: Build Javadocs
          run: |
            echo "Building javadocs with gradle"
            ./gradlew javadoc
            echo "Moving to javadocs directory:"
            cd build/docs/javadoc/
            echo "Creating .nojekyll to have Github pages deploy html as is:"
            cp -rf build/docs/javadoc/. docs/api	
