name: Javadoc Check
on: workflow_dispatch

jobs:
  javadoc_generate:
    runs-on: ubuntu-latest

    steps:
      # masterブランチをチェックアウト
      - uses: actions/checkout@v2

      # JDKの設定
      - name: Set up JDK 1.8
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      # Gradleへの権限付与
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Javadoc生成
      - name: Build javadoc
        run: |
           ! ./gradlew :first:javadoc 2>&1 | grep -v 'warning: \\[deprecation\\]' | grep -A 2 -e warning: -e error:
           build1=$?
           ! ./gradlew :second:javadoc 2>&1 | grep -v 'warning: \\[deprecation\\]' | grep -A 2 -e warning: -e error:
           build2=$?
           if [ $build1 -eq 1 ] || [ $build2 -eq 1 ]; then
             exit 1
           else
             exit 0
           fi
           
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
