name: Automatically Deploy Javadocs

on:
  push:
    branches: [ main ]

jobs:
   build:

      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Javadocs
        run: |
         echo "Building javadocs with gradle"
         ./gradlew javadoc
         echo "Moving to javadocs directory:"
         cd build/docs/javadoc/
         echo "Creating .nojekyll to have Github pages deploy html as is:"
         touch .nojekyll
         
      #- name: Deploy
      #  uses: JamesIves/github-pages-deploy-action@4.0.0
      #  with:
      #    branch: javadocTest # The branch the action should deploy to.
      #    folder: build/docs/javadoc/ # The folder the action should deploy.
      
      # clean up the javadoc files including removing timestamps. OPTIONAL.
      - name: Tidy up the javadocs
        id: tidy
        uses: cicirello/javadoc-cleanup@v1
        with:
          path-to-root: docs
 
      # store the doc files
      - name: Upload Output Directory
        uses: actions/upload-artifact@v2
        with:
          name: doc-files
          path: docs
          retention-days: 1

   copy:
     runs-on: ubuntu-latest
     needs: build
     steps:
       # checkout the gh-pages branch
       - uses: actions/checkout@v2
         with:
           ref: main
           # download the doc files, most of which are generated above
       - name: Download Output Directory
         uses: actions/download-artifact@v2
         with:
           name: doc-files
           path: docs
       # add, commit and push to gh-pages
       - name: Commit changes
         uses: EndBug/add-and-commit@v7
         with:
          author_name: test
          author_email: terawaki.t.saze@gmail.com
          message: 'Update docs'
          branch: main
          add: 'docs'
