name: Javadoc Check
on:
  push:
    branches: [ plus** ]
    paths: 
    - 'src'

jobs:
  javadoc_generate:
    runs-on: ubuntu-latest

    steps:
      # masterブランチをチェックアウト
      - uses: actions/checkout@v2

      # JDKの設定
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Gradleへの権限付与
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Javadoc生成
      - name: Build javadoc
        run: |
          ! ./gradlew javadoc 2>&1 | grep -v 'warning: \\[deprecation\\]' | grep -A 2 -e warning: -e error: ; exit $?
