name: GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src/react/
          output_dir: ./docs
      - name: Update API docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update API docs
          repository: ./docs/
