name: test
on: 
  workflow_dispatch

jobs:
  javadoc_generate:
    runs-on: ubuntu-latest

    env:
      # javadoc用ブランチ名
      BRANCH_JAVADOC: javadocOnly
      BRANCH_JAVADOC_ORIGIN: origin/javadocOnly
      # masterブランチ名
      BRANCH_MASTER: develop
      BRANCH_MASTER_ORIGIN: origin/develop

    steps:
      # masterブランチをチェックアウト
      - uses: actions/checkout@v2
        with:
          ref: ${{env.BRANCH_MASTER}}

      # git configの設定
      - uses: fregante/setup-git-user@v1

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
