name: plusActionTest
on:
  workflow_dispatch

jobs:
   build:
      runs-on: ubuntu-latest      
      steps:

      # javadoc専用ブランチの存在確認
      - name: Check javadoc branch exist
        run: |
          git branch -a --format="%(refname:short)"

