name: plusActionTest
on:
  workflow_dispatch

jobs:
   build:
      runs-on: ubuntu-latest      
      steps:
      # mainブランチのソースをチェックアウト
      - uses: actions/checkout@v2
        with:
          ref: 'main'

      # javadoc専用ブランチの存在確認
      - name: Check javadoc branch exist
        id: check
        run: git branch -a | grep -v 'javadocOnly'
      
      - name: Check javadoc branch exist
        if: steps.check.conclusion == ''
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b javadocOnly
          git push origin javadocOnly
