name: plusActionTest
on:
  workflow_dispatch

jobs:
   build:
      runs-on: ubuntu-latest      
      steps:
      # mainブランチのソースをチェックアウト
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      # javadoc専用ブランチの存在確認
      - id: check
        run: |
          git fetch
          echo "##[set-output name=result;] git branch -a --format="%(refname:short)" | grep -e javadocOnly" 

      - name: Check javadoc branch exist
        env:
          RESULT: ${{steps.check.outputs.branch}}
        run: |
          echo ${{ steps.check.outputs.branch }}
          echo $RESULT
