name: plusActionTest
on:
  workflow_dispatch

jobs:
   build:
      runs-on: ubuntu-latest      
      steps:
      # mainブランチのソースをチェックアウト
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          
      # javadoc専用ブランチの存在確認
      - id: check
        run: |
          git fetch
          echo "##[set-output name=branch;]$(git branch -a --format="%(refname:short)" | grep -e javadocOnly)" 

      # javadoc専用ブランチがあればmasterのソースに更新
      - name: Check javadoc branch exist
        if: (steps.check.outputs.branch == 'origin/javadocOnly')
        run: |
          # 開発用ブランチへ移動
          git checkout javadocOnly
          # mergeコマンドでmaserの内容を取り込む
          git merge origin master

      # javadoc専用ブランチがなければmasterのソースをもとに作成
      - name: Check javadoc branch not exist
        if: "!(steps.check.outputs.branch == 'origin/javadocOnly')"
        run: |
          # javadoc専用ブランチを作成
          git checkout -b javadocOnly
          # mainブランチのソースをjavadoc専用ブランチにpush
          git push origin javadocOnly
