name: plusActionTest
on:
  workflow_dispatch

jobs:
   build:
      runs-on: ubuntu-latest      
      steps:
      # mainブランチのソースをチェックアウト
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      # javadoc専用ブランチの存在確認
      - id: check
        run: |
          git fetch
          echo "##[set-output name=branch;]$(git branch -a --format="%(refname:short)" | grep -e javadocOnly)" 

      - name: Check javadoc branch exist
        if: (steps.check.outputs.branch == 'origin/javadocOnly')
        run: |
          echo 'branch exist'

      - name: Check javadoc branch not exist
        if: "!(steps.check.outputs.branch == 'origin/javadocOnly')"
        run: |
          git checkout -b javadocOnly
          git push origin javadocOnly
