name: plusActionTest
on:
  workflow_dispatch

jobs:
   build:
      runs-on: ubuntu-latest      
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Javadocs
        run: |
         ! ./gradlew javadoc 2>&1 | grep -v 'warning: \\[deprecation\\]' | grep -A 2 -e warning: -e error: ; exit $?
         cd build/docs/javadoc/
      
      - name: Cleanup
        run: |
          rm -rf ./docs/*
          cp -r build/docs/javadoc/* ./docs/
      - name: Update API docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: javadocOnly
          commit_message: Update javadoc documents
          repository: ./docs/
