name: plusActionTest
on:
  workflow_dispatch

jobs:
   build:
      runs-on: ubuntu-latest      
      steps:
      # mainブランチのソースをチェックアウト
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      # javadoc専用ブランチの存在確認
      - id: check
        run: |
          git fetch
          git branch -a --format="%(refname:short)" | grep -e javadocOnly

      - name: Check javadoc branch exist
        run: echo steps.check.conclusion
      
      - name: Check javadoc branch exist
        if: steps.check.conclusion == ''
        run: echo 'not exist'
        
      - name: check javadoc branch exist 2
        if: steps.check.conclusion == 'origin/javadocOnly'
        run: echo 'year exist'
